name: run main.py

on:
  schedule:
  - cron: "42 3 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        # Install a specific version of uv.
        version: "0.11.17"

    - name: execute py script
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: uv run main.py

    - name: commit files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -a -m "updated files" || echo "Nothing to commit"
        git push
